### ISSUE TITLE
colors and @babel/types

### ISSUE THREAD

**Issue by pitust** [coder-mike/microvium#2]
These are dependencies, however they are not included by default in package.json for some reason.

**Comment by coder-mike** [comment]
I can see them listed in the `devDependencies`. Certainly, I should move `colors` to the dependencies, but `@babel/types` shouldn't be a runtime dependency since the package entry points are JavaScript not TypeScript. Let me know if you disagree.

**Comment by pitust** [comment]
Umm... When I got microvium off npm it crashed until i got `@babel/types`.

**Comment by coder-mike** [comment]
Ok, I'm able to reproduce the same issue with microvium as a library. Perhaps, for some strange reason, `@babel/types` is more than just types. Anyway, I'll include it in the dependencies and the problem will go away. Thanks for uncovering this.

**Comment by pitust** [comment]
I think i had propblems with both; but for disk-space reasons i use PNPM instead of NPM. So perhaps one of your dependencies had it but PNPM didn't give it to you because it wasn't in your node_modules
