### ISSUE TITLE
Eval line in tutorial does not work if the shell is bash

### ISSUE THREAD

**Issue by davidchisnall** [coder-mike/microvium#22]
This line:

> microvium --eval "console.log('Hello, World!')"

Causes problems because the `!` is inside double quotes and so is subject to shell script parsing.  The `!` token instructs the shell to evaluate the last command matching the pattern `')` and so you will get a surprising shell error when you run this.  Flipping the quotes works fine:

```
$ microvium --eval 'console.log("Hello, World!")'
Hello, World!
Output generated: script.mvm-bc
72 bytes
$ microvium --eval "console.log('Hello, World!')"
bash: !': event not found
```

**Comment by coder-mike** [comment]
Thank you!
