### ISSUE TITLE
npm run build fails in sync-opcodes.ts

### ISSUE THREAD

**Issue by bshanks** [coder-mike/microvium#25]
$ npm --version
8.5.1
$ cd /tmp
$ git clone https://github.com/coder-mike/microvium.git
$ cd microvium
$ npm install typescript
$ ts-node --version
v9.1.1
$ npm run build

> microvium@0.0.18 build
> ts-node scripts/sync-opcodes.ts && node-gyp build --debug && tsc && ts-node scripts/preprocess-microvium && npm run copy-files && npm run size-check

/tmp/microvium/scripts/sync-opcodes.ts:74
    throw new Error('Error synchronizing. Source pattern not found');
          ^
Error: Error synchronizing. Source pattern not found
    at copyInto (/tmp/microvium/scripts/sync-opcodes.ts:74:11)
    at Object.<anonymous> (/tmp/microvium/scripts/sync-opcodes.ts:64:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/tmp/microvium/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/tmp/microvium/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/tmp/microvium/node_modules/ts-node/src/bin.ts:227:14)

**Comment by coder-mike** [comment]
If I try to reproduce your steps, I get a different error:

```
gyp ERR! stack Error: You must run `node-gyp configure` first!
```

So I'm not sure quite how it got so far without node-gyp configure. But anyway, can you please try the following commands:

```
cd /tmp
git clone https://github.com/coder-mike/microvium.git
cd microvium
npm install      # <-- Not just typescript
npm run build
```

The `npm install` will install `ts-node` locally as well, so you shouldn't need it globally. It should also trigger the node-gyp configuration. Let me know if you're still running into issues.

**Comment by bshanks** [comment]
Thanks, the issue still occurs:

$ npm install
npm WARN deprecated @types/immutable@3.8.7: This is a stub types definition for Facebook's Immutable (https://github.com/facebook/immutable-js). Facebook's Immutable provides its own type definitions, so you don't need @types/immutable installed!
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> microvium@0.0.18 install
> node-gyp-build

gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.22.9 | linux | x64
gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/tmp/microvium/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/microvium/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/microvium/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/bshanks/.cache/node-gyp/12.22.9/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/bshanks/.cache/node-gyp/12.22.9',
gyp info spawn args   '-Dnode_gyp_dir=/tmp/microvium/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/bshanks/.cache/node-gyp/12.22.9/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/microvium',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/tmp/microvium/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/native-vm/native-vm-bindings/index.o
In file included from ../native-vm-bindings/../native-vm/microvium_port_test.h:11,
                 from ../native-vm-bindings/microvium_port.h:1,
                 from ../native-vm-bindings/../native-vm/microvium.h:14,
                 from ../native-vm-bindings/Value.hh:4,
                 from ../native-vm-bindings/index.cc:1:
../native-vm-bindings/../native-vm/microvium_port_example.h:235:17: warning: ‘uint16_t crc16(void*, uint16_t)’ defined but not used [-Wunused-function]
  235 | static uint16_t crc16(MVM_LONG_PTR_TYPE lp, uint16_t size) {
      |                 ^~~~~
  CXX(target) Release/obj.target/native-vm/native-vm-bindings/NativeVM.o
../native-vm-bindings/NativeVM.cc: In member function ‘void VM::NativeVM::runGC(const Napi::CallbackInfo&)’:
../native-vm-bindings/NativeVM.cc:127:8: warning: variable ‘env’ set but not used [-Wunused-but-set-variable]
  127 |   auto env = info.Env();
      |        ^~~
In file included from ../native-vm-bindings/../native-vm/microvium_port_test.h:11,
                 from ../native-vm-bindings/microvium_port.h:1,
                 from ../native-vm-bindings/../native-vm/microvium.h:14,
                 from ../native-vm-bindings/NativeVM.hh:6,
                 from ../native-vm-bindings/NativeVM.cc:3:
../native-vm-bindings/../native-vm/microvium_port_example.h: At global scope:
../native-vm-bindings/../native-vm/microvium_port_example.h:235:17: warning: ‘uint16_t crc16(void*, uint16_t)’ defined but not used [-Wunused-function]
  235 | static uint16_t crc16(MVM_LONG_PTR_TYPE lp, uint16_t size) {
      |                 ^~~~~
  CXX(target) Release/obj.target/native-vm/native-vm-bindings/Value.o
In file included from ../native-vm-bindings/../native-vm/microvium_port_test.h:11,
                 from ../native-vm-bindings/microvium_port.h:1,
                 from ../native-vm-bindings/../native-vm/microvium.h:14,
                 from ../native-vm-bindings/Value.hh:4,
                 from ../native-vm-bindings/Value.cc:1:
../native-vm-bindings/../native-vm/microvium_port_example.h:235:17: warning: ‘uint16_t crc16(void*, uint16_t)’ defined but not used [-Wunused-function]
  235 | static uint16_t crc16(MVM_LONG_PTR_TYPE lp, uint16_t size) {
      |                 ^~~~~
  CXX(target) Release/obj.target/native-vm/native-vm-bindings/misc.o
In file included from ../native-vm-bindings/../native-vm/microvium_port_test.h:11,
                 from ../native-vm-bindings/microvium_port.h:1,
                 from ../native-vm-bindings/../native-vm/microvium.h:14,
                 from ../native-vm-bindings/error_descriptions.hh:3,
                 from ../native-vm-bindings/misc.cc:1:
../native-vm-bindings/../native-vm/microvium_port_example.h:235:17: warning: ‘uint16_t crc16(void*, uint16_t)’ defined but not used [-Wunused-function]
  235 | static uint16_t crc16(MVM_LONG_PTR_TYPE lp, uint16_t size) {
      |                 ^~~~~
  CXX(target) Release/obj.target/native-vm/native-vm-bindings/WeakRef.o
  CXX(target) Release/obj.target/native-vm/native-vm-bindings/error_descriptions.o
In file included from ../native-vm-bindings/../native-vm/microvium_port_test.h:11,
                 from ../native-vm-bindings/microvium_port.h:1,
                 from ../native-vm-bindings/../native-vm/microvium.h:14,
                 from ../native-vm-bindings/error_descriptions.hh:3,
                 from ../native-vm-bindings/error_descriptions.cc:1:
../native-vm-bindings/../native-vm/microvium_port_example.h:235:17: warning: ‘uint16_t crc16(void*, uint16_t)’ defined but not used [-Wunused-function]
  235 | static uint16_t crc16(MVM_LONG_PTR_TYPE lp, uint16_t size) {
      |                 ^~~~~
  CC(target) Release/obj.target/native-vm/native-vm/microvium.o
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium_internals.h:439:48: warning: left shift of negative value [-Wshift-negative-value]
  439 | #define VIRTUAL_INT14_ENCODE(i) ((uint16_t)((i << 2) | 3))
      |                                                ^~
../native-vm/microvium_internals.h:822:29: note: in expansion of macro ‘VIRTUAL_INT14_ENCODE’
  822 |   /* VM_SLV_INT_MINUS_1 */  VIRTUAL_INT14_ENCODE(-1),
      |                             ^~~~~~~~~~~~~~~~~~~~
../native-vm/microvium.c: In function ‘mvm_call’:
../native-vm/microvium_internals.h:234:73: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  234 | #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:514:3: note: in expansion of macro ‘VM_ASSERT_UNREACHABLE’
  514 |   VM_ASSERT_UNREACHABLE(vm);
      |   ^~~~~~~~~~~~~~~~~~~~~
../native-vm/microvium_internals.h:234:73: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  234 | #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:979:3: note: in expansion of macro ‘VM_ASSERT_UNREACHABLE’
  979 |   VM_ASSERT_UNREACHABLE(vm);
      |   ^~~~~~~~~~~~~~~~~~~~~
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium_internals.h:215:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  215 | #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:1356:7: note: in expansion of macro ‘VM_NOT_IMPLEMENTED’
 1356 |       VM_NOT_IMPLEMENTED(vm);
      |       ^~~~~~~~~~~~~~~~~~
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium_internals.h:234:73: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  234 | #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:1421:3: note: in expansion of macro ‘VM_ASSERT_UNREACHABLE’
 1421 |   VM_ASSERT_UNREACHABLE(vm);
      |   ^~~~~~~~~~~~~~~~~~~~~
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium_internals.h:215:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  215 | #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:1625:7: note: in expansion of macro ‘VM_NOT_IMPLEMENTED’
 1625 |       VM_NOT_IMPLEMENTED(vm);
      |       ^~~~~~~~~~~~~~~~~~
../native-vm/microvium_internals.h:215:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  215 | #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:1638:7: note: in expansion of macro ‘VM_NOT_IMPLEMENTED’
 1638 |       VM_NOT_IMPLEMENTED(vm);
      |       ^~~~~~~~~~~~~~~~~~
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium_internals.h:234:73: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  234 | #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:1644:3: note: in expansion of macro ‘VM_ASSERT_UNREACHABLE’
 1644 |   VM_ASSERT_UNREACHABLE(vm);
      |   ^~~~~~~~~~~~~~~~~~~~~
../native-vm/microvium.c:92:20: warning: operation on ‘pStackPointer’ may be undefined [-Wsequence-point]
   92 |     *(pStackPointer++) = (v); \
      |      ~~~~~~~~~~~~~~^~~
../native-vm/microvium.c:104:5: note: in expansion of macro ‘PUSH’
  104 |     PUSH((uint16_t)(uintptr_t)pStackPointer - (uint16_t)(uintptr_t)pFrameBase); \
      |     ^~~~
../native-vm/microvium.c:1940:3: note: in expansion of macro ‘PUSH_REGISTERS’
 1940 |   PUSH_REGISTERS(regLP1);
      |   ^~~~~~~~~~~~~~
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium.c: In function ‘vm_getStringData’:
../native-vm/microvium_internals.h:234:73: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  234 | #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:4250:7: note: in expansion of macro ‘VM_ASSERT_UNREACHABLE’
 4250 |       VM_ASSERT_UNREACHABLE(vm);
      |       ^~~~~~~~~~~~~~~~~~~~~
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium.c: In function ‘getProperty’:
../native-vm/microvium_internals.h:215:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  215 | #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:4421:9: note: in expansion of macro ‘VM_NOT_IMPLEMENTED’
 4421 |         VM_NOT_IMPLEMENTED(vm);
      |         ^~~~~~~~~~~~~~~~~~
../native-vm/microvium.c:4491:19: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 4491 |         if (index < 0) {
      |                   ^
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium.c: In function ‘setProperty’:
../native-vm/microvium_internals.h:215:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  215 | #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:4603:9: note: in expansion of macro ‘VM_NOT_IMPLEMENTED’
 4603 |         VM_NOT_IMPLEMENTED(vm);
      |         ^~~~~~~~~~~~~~~~~~
../native-vm/microvium.c:4761:19: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 4761 |         if (index < 0) {
      |                   ^
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium.c: In function ‘vm_stringSizeUtf8’:
../native-vm/microvium_internals.h:234:73: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  234 | #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:5039:7: note: in expansion of macro ‘VM_ASSERT_UNREACHABLE’
 5039 |       VM_ASSERT_UNREACHABLE(vm);
      |       ^~~~~~~~~~~~~~~~~~~~~
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium.c: In function ‘toInt32Internal’:
../native-vm/microvium_internals.h:215:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  215 | #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:5093:7: note: in expansion of macro ‘VM_NOT_IMPLEMENTED’
 5093 |       VM_NOT_IMPLEMENTED(vm); break;
      |       ^~~~~~~~~~~~~~~~~~
../native-vm/microvium_internals.h:215:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  215 | #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:5097:7: note: in expansion of macro ‘VM_NOT_IMPLEMENTED’
 5097 |       VM_NOT_IMPLEMENTED(vm); break;
      |       ^~~~~~~~~~~~~~~~~~
../native-vm/microvium_internals.h:215:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  215 | #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:5101:7: note: in expansion of macro ‘VM_NOT_IMPLEMENTED’
 5101 |       VM_NOT_IMPLEMENTED(vm); break;
      |       ^~~~~~~~~~~~~~~~~~
../native-vm/microvium_internals.h:215:75: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  215 | #define VM_NOT_IMPLEMENTED(vm) (MVM_FATAL_ERROR(vm, MVM_E_NOT_IMPLEMENTED), -1)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:5105:7: note: in expansion of macro ‘VM_NOT_IMPLEMENTED’
 5105 |       VM_NOT_IMPLEMENTED(vm); break;
      |       ^~~~~~~~~~~~~~~~~~
../native-vm/microvium_internals.h:216:63: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  216 | #define VM_RESERVED(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:5129:7: note: in expansion of macro ‘VM_RESERVED’
 5129 |       VM_RESERVED(vm); break;
      |       ^~~~~~~~~~~
../native-vm/microvium_internals.h:216:63: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  216 | #define VM_RESERVED(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:5133:7: note: in expansion of macro ‘VM_RESERVED’
 5133 |       VM_RESERVED(vm); break;
      |       ^~~~~~~~~~~
In file included from ../native-vm/microvium.c:39:
../native-vm/microvium_internals.h:234:73: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  234 | #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:5172:7: note: in expansion of macro ‘VM_ASSERT_UNREACHABLE’
 5172 |       VM_ASSERT_UNREACHABLE(vm);
      |       ^~~~~~~~~~~~~~~~~~~~~
../native-vm/microvium.c: In function ‘mvm_equal’:
../native-vm/microvium_internals.h:234:73: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  234 | #define VM_ASSERT_UNREACHABLE(vm) (MVM_FATAL_ERROR(vm, MVM_E_UNEXPECTED), -1)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../native-vm/microvium.c:5388:7: note: in expansion of macro ‘VM_ASSERT_UNREACHABLE’
 5388 |       VM_ASSERT_UNREACHABLE(vm);
      |       ^~~~~~~~~~~~~~~~~~~~~
../native-vm/microvium.c: At top level:
../native-vm/microvium_internals.h:768:13: warning: ‘loadPtr’ declared ‘static’ but never defined [-Wunused-function]
  768 | static void loadPtr(VM* vm, uint8_t* heapStart, Value* pValue);
      |             ^~~~~~~
../native-vm/microvium.c: In function ‘mvm_call’:
../native-vm/microvium.c:1975:20: warning: ‘reg1F’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1975 |       reg1 = reg1F > reg2F;
      |              ~~~~~~^~~~~~~
  SOLINK_MODULE(target) Release/obj.target/native-vm.node
  COPY Release/native-vm.node
make: Leaving directory '/tmp/microvium/build'
gyp info ok 

added 338 packages, and audited 339 packages in 7s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ npm run build

> microvium@0.0.18 build
> ts-node scripts/sync-opcodes.ts && node-gyp build --debug && tsc && ts-node scripts/preprocess-microvium && npm run copy-files && npm run size-check


/tmp/microvium/scripts/sync-opcodes.ts:74
    throw new Error('Error synchronizing. Source pattern not found');
          ^
Error: Error synchronizing. Source pattern not found
    at copyInto (/tmp/microvium/scripts/sync-opcodes.ts:74:11)
    at Object.<anonymous> (/tmp/microvium/scripts/sync-opcodes.ts:64:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/tmp/microvium/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/tmp/microvium/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/tmp/microvium/node_modules/ts-node/src/bin.ts:227:14)

**Comment by bshanks** [comment]
I'm on GNU/Linux pop-os 22.04. The offending call to copyInto in sync-opcodes.ts is:

tsSnapshotIL = copyInto(cMicroviumBytecode, tsSnapshotIL,
  '#define MVM_BYTECODE_VERSION ', '\r\n',
  'export const BYTECODE_VERSION = ', ';');

I think the \r\n is the Windows-specific newline delimiter, perhaps that's messing it up?

**Comment by coder-mike** [comment]
Yes, that last error is benign. I decided that because an objective Microvium is to be small, I would measure the size after each build.

**Comment by coder-mike** [comment]
Thanks for your help diagnosing this. I believe I've fixed both issues now -- just a `chmod` for those scripts, and the change to the newline to support both Windows and Linux. Would you mind running everything again and seeing if it works now?

**Comment by bshanks** [comment]
It gets thru most of the build, but at the end it doesn't print "Microvium flash size:  8.22 kB"
anymore, instead there are a few new errors:

> bash ./size-test.sh

/tmp/microvium/size-test /tmp/microvium
./build.sh: line 4: arm-none-eabi-gcc: command not found
./build.sh: line 14: arm-none-eabi-objdump: command not found
./build.sh: line 15: arm-none-eabi-objdump: command not found
./build.sh: line 16: arm-none-eabi-size: command not found

**Comment by bshanks** [comment]
I'd also suggest mentioning "npm install" in doc/contribute.md

**Comment by coder-mike** [comment]
Ok, the new errors actually show it's getting further :-)

What's happening is that the size measurement is using the GCC compiler for the Cortex M0. Maybe I should make that step conditional on an environment variable.

**Comment by coder-mike** [comment]
I've made a note `contribute.md`. I also recommend installing the [ARM GNU Toolchain](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/downloads) so that the size tests work, if your intention is to contribute, since we want to keep a close eye on how the changes affect the size.

**Comment by bshanks** [comment]
Thanks!
