### ISSUE TITLE
Update example code on the website

### ISSUE THREAD

**Issue by boogie** [coder-mike/microvium#29]
The website has an outdated bytecode, and it was not clear for me what's wrong: :)
https://microvium.com/getting-started/

**Comment by coder-mike** [comment]
Yeah, I haven't deployed to the website in a while because I think everyone was using the github repo directly. But I'll take this as an impetus to update the website.

**Comment by coder-mike** [comment]
I've updated it. Thanks for letting me know. 

Let me know if you have any more issues.
