### ISSUE TITLE
GCC 10 tests fail

### ISSUE THREAD

**Issue by pitust** [coder-mike/microvium#6]
Tests fail when the compiler is GCC 10 due to the warning `-Wpointer-to-int-cast`

**Comment by coder-mike** [comment]
Is that with `-Werror`? Otherwise I wouldn't expect a warning to be a failure. Is there a way to just disable the warning for the file?

**Comment by pitust** [comment]
The issue is that there is an assertDeepEqual on stderror. So tests fail. I have fixed these issues, and I can send a PR in a bit. (when i fix some other issues)

**Comment by coder-mike** [comment]
Ah, awesome. Thanks for the input!

**Comment by coder-mike** [comment]
Closing this issue as outdated
