### ISSUE TITLE
strcpy_s not standard

### ISSUE THREAD

**Issue by hiperiondev** [coder-mike/microvium#72]
strcpy_s is not a standard function, I understand that it is a function of Microsoft Visual C / C ++
This is not portable, and in fact does not exist in the ESP-IDF.
Should be replaced by a standard function or provide an implementation

**Comment by hiperiondev** [comment]
May be from here https://sourceforge.net/projects/safeclib/

**Comment by hiperiondev** [comment]
I see there is only one use and it is static.
Better to replace by:
memcpy(p, "Infinity", 9);

**Comment by coder-mike** [comment]
Ah yeah. I changed it to `strncpy` but actually `memcpy` is better. Thanks for the idea!
