### ISSUE TITLE
int32_t is a long int

### ISSUE THREAD

**Issue by hiperiondev** [coder-mike/microvium#73]
In static Value vm_intToStr(VM* vm, int32_t i):
  size = MVM_SNPRINTF(buf, sizeof buf, "%d", i);

must be:

  size = MVM_SNPRINTF(buf, sizeof buf, "%ld", i);

**Comment by coder-mike** [comment]
Ah yeah, thanks. Should be fixed now!

**Comment by davidchisnall** [comment]
The correct way of doing this is with the PRId32 macro. On LP64 platforms, coercing to long is inefficient.

**Comment by coder-mike** [comment]
Ah yeah, good call. Thanks @davidchisnall!
